# Generated by Django 3.2.25 on 2025-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_hora_creacion_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
