# Generated by Django 3.2.25 on 2025-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacion_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='img',
        ),
    ]
