# Generated by Django 3.2.25 on 2025-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_publicacion_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
